[program:vacaciones]
command=/var/www/html/vacaciones/deploy/gunicorn.sh
autostart=true
autorestart=true
stderr_logfile=/var/www/html/vacaciones/deploy/err.log
stdout_logfile=/var/www/html/vacaciones/deploy/out.log
user=odooapps
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8