# Generated by Django 4.2 on 2026-05-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FULL_DAY', 'Día completo'), ('PARTIAL', 'Acumulable')], max_length=10)),
                ('partial_type', models.CharField(blank=True, choices=[('LATE', 'Llegada tarde'), ('EARLY_LEAVE', 'Salida en horas de trabajo')], max_length=15, null=True)),
                ('date', models.DateField()),
                ('event_time', models.TimeField(blank=True, help_text='Hora de llegada tarde o de salida anticipada (solo acumulables).', null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_LEADER', 'Pendiente de líder'), ('PENDING_HR', 'Pendiente de RH'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='PENDING_LEADER', max_length=20)),
                ('origin', models.CharField(choices=[('EMPLOYEE', 'Trabajador'), ('LEADER', 'Líder')], default='EMPLOYEE', max_length=10)),
                ('leader_acted_at', models.DateTimeField(blank=True, null=True)),
                ('hr_acted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests_cancelled', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
                ('hr_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests_hr_acted', to=settings.AUTH_USER_MODEL)),
                ('leader_acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests_leader_acted', to=settings.AUTH_USER_MODEL)),
                ('requested_to_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests_to_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['employee', 'date'], name='vacations_v_employe_8e4713_idx'),
        ),
        migrations.AddIndex(
            model_name='vacationrequest',
            index=models.Index(fields=['status'], name='vacations_v_status_bfd02b_idx'),
        ),
    ]
